import pymongo
from logging_utils import log_error
from _config import EQ_EQUITY_LONG_SHORT_PROMPT, EQ_EQUITY_FACTORS_PROMPT

def insert_equities(db):
    """
    Inserts global equities into the 'tickers' collection.
    
    Args:
        db: MongoDB database object
        
    Returns:
        bool: True if insertion was successful, False on error
    """
    collection_name = 'tickers'
    
    print()
    print("=" * 100)
    print(f"Inserting equities into '{collection_name}' collection...")
    print("=" * 100)
    print()
    
    
    # Equities data to insert with prompt and model_function fields
    equities = [
        {"ticker": "WTO", "ticker_tradingview": "NASDAQ:WTO", "name": "UTime Limited", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "APLT", "ticker_tradingview": "NASDAQ:APLT", "name": "Applied Therapeutics, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AMIX", "ticker_tradingview": "NASDAQ:AMIX", "name": "Autonomix Medical, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "KXIN", "ticker_tradingview": "NASDAQ:KXIN", "name": "Kaixin Holdings", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NVDA", "ticker_tradingview": "NASDAQ:NVDA", "name": "NVIDIA Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "OPEN", "ticker_tradingview": "NASDAQ:OPEN", "name": "Opendoor Technologies Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ONDS", "ticker_tradingview": "NASDAQ:ONDS", "name": "Ondas Holdings Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CHR", "ticker_tradingview": "NASDAQ:CHR", "name": "Cheer Holding, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ASST", "ticker_tradingview": "NASDAQ:ASST", "name": "Asset Entities Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TSLA", "ticker_tradingview": "NASDAQ:TSLA", "name": "Tesla, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GLMD", "ticker_tradingview": "NASDAQ:GLMD", "name": "Galmed Pharmaceuticals Ltd.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CYPH", "ticker_tradingview": "OTCMKTS:CYPH", "name": "Cypherpunk Technologies Inc. Common Stock", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PLUG", "ticker_tradingview": "NASDAQ:PLUG", "name": "Plug Power Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BAC", "ticker_tradingview": "NYSE:BAC", "name": "Bank of America Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BABA", "ticker_tradingview": "NYSE:BABA", "name": "Alibaba Group Holding Limited", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AMZN", "ticker_tradingview": "NASDAQ:AMZN", "name": "Amazon.com, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "QQQ", "ticker_tradingview": "NASDAQ:QQQ", "name": "Invesco QQQ Trust, Series 1", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GOOGL", "ticker_tradingview": "NASDAQ:GOOGL", "name": "Alphabet Inc. (Class A)", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AAPL", "ticker_tradingview": "NASDAQ:AAPL", "name": "Apple Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MSFT", "ticker_tradingview": "NASDAQ:MSFT", "name": "Microsoft Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "META", "ticker_tradingview": "NASDAQ:META", "name": "Meta Platforms, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AMD", "ticker_tradingview": "NASDAQ:AMD", "name": "Advanced Micro Devices, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PBR", "ticker_tradingview": "NYSE:PBR", "name": "Petróleo Brasileiro S.A. - Petrobras", "region": ["US", "BR"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "INTC", "ticker_tradingview": "NASDAQ:INTC", "name": "Intel Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MULN", "ticker_tradingview": "NASDAQ:MULN", "name": "Mullen Automotive, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "F", "ticker_tradingview": "NYSE:F", "name": "Ford Motor Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SIRI", "ticker_tradingview": "NASDAQ:SIRI", "name": "Sirius XM Holdings Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PLTR", "ticker_tradingview": "NASDAQ:PLTR", "name": "Palantir Technologies Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PFE", "ticker_tradingview": "NYSE:PFE", "name": "Pfizer Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "UBER", "ticker_tradingview": "NYSE:UBER", "name": "Uber Technologies, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "JNJ", "ticker_tradingview": "NYSE:JNJ", "name": "Johnson & Johnson", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "XOM", "ticker_tradingview": "NYSE:XOM", "name": "Exxon Mobil Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MSI", "ticker_tradingview": "NYSE:MSI", "name": "Motorola Solutions, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WBD", "ticker_tradingview": "NASDAQ:WBD", "name": "Warner Bros. Discovery, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GME", "ticker_tradingview": "NYSE:GME", "name": "GameStop Corp.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "HOOD", "ticker_tradingview": "NASDAQ:HOOD", "name": "Robinhood Markets, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WTI", "ticker_tradingview": "NYSE:WTI", "name": "W&T Offshore, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NKE", "ticker_tradingview": "NYSE:NKE", "name": "NIKE, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "KO", "ticker_tradingview": "NYSE:KO", "name": "The Coca-Cola Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "T", "ticker_tradingview": "NYSE:T", "name": "AT&T Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "VZ", "ticker_tradingview": "NYSE:VZ", "name": "Verizon Communications Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MCD", "ticker_tradingview": "NYSE:MCD", "name": "McDonald's Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "HD", "ticker_tradingview": "NYSE:HD", "name": "The Home Depot, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PYPL", "ticker_tradingview": "NASDAQ:PYPL", "name": "PayPal Holdings, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DIS", "ticker_tradingview": "NYSE:DIS", "name": "The Walt Disney Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WMT", "ticker_tradingview": "NYSE:WMT", "name": "Walmart Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MA", "ticker_tradingview": "NYSE:MA", "name": "Mastercard Incorporated", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "V", "ticker_tradingview": "NYSE:V", "name": "Visa Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CRM", "ticker_tradingview": "NYSE:CRM", "name": "Salesforce, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BA", "ticker_tradingview": "NYSE:BA", "name": "The Boeing Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WFC", "ticker_tradingview": "NYSE:WFC", "name": "Wells Fargo & Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CSCO", "ticker_tradingview": "NASDAQ:CSCO", "name": "Cisco Systems, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ABT", "ticker_tradingview": "NYSE:ABT", "name": "Abbott Laboratories", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "COST", "ticker_tradingview": "NASDAQ:COST", "name": "Costco Wholesale Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DOW", "ticker_tradingview": "NYSE:DOW", "name": "Dow Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "HPQ", "ticker_tradingview": "NYSE:HPQ", "name": "HP Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GE", "ticker_tradingview": "NYSE:GE", "name": "General Electric Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SBUX", "ticker_tradingview": "NASDAQ:SBUX", "name": "Starbucks Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DELL", "ticker_tradingview": "NYSE:DELL", "name": "Dell Technologies Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PTON", "ticker_tradingview": "NASDAQ:PTON", "name": "Peloton Interactive, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RIVN", "ticker_tradingview": "NASDAQ:RIVN", "name": "Rivian Automotive, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LCID", "ticker_tradingview": "NASDAQ:LCID", "name": "Lucid Group, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "COIN", "ticker_tradingview": "NASDAQ:COIN", "name": "Coinbase Global, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SNAP", "ticker_tradingview": "NYSE:SNAP", "name": "Snap Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DKNG", "ticker_tradingview": "NASDAQ:DKNG", "name": "DraftKings Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CLOV", "ticker_tradingview": "NASDAQ:CLOV", "name": "Clover Health Investments, Corp.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TLRY", "ticker_tradingview": "NASDAQ:TLRY", "name": "Tilray Brands, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MS", "ticker_tradingview": "NYSE:MS", "name": "Morgan Stanley", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "C", "ticker_tradingview": "NYSE:C", "name": "Citigroup Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "JPM", "ticker_tradingview": "NYSE:JPM", "name": "JPMorgan Chase & Co.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CAT", "ticker_tradingview": "NYSE:CAT", "name": "Caterpillar Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BRK.B", "ticker_tradingview": "NYSE:BRK.B", "name": "Berkshire Hathaway Inc. (Class B)", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LLY", "ticker_tradingview": "NYSE:LLY", "name": "Eli Lilly and Company", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TSM", "ticker_tradingview": "NYSE:TSM", "name": "Taiwan Semiconductor Manufacturing Company Limited", "region": ["US", "TW"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BILI", "ticker_tradingview": "NASDAQ:BILI", "name": "Bilibili Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CGC", "ticker_tradingview": "NASDAQ:CGC", "name": "Canopy Growth Corporation", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "KGC", "ticker_tradingview": "NYSE:KGC", "name": "Kinross Gold Corporation", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "FCX", "ticker_tradingview": "NYSE:FCX", "name": "Freeport-McMoRan Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AUY", "ticker_tradingview": "NYSE:AUY", "name": "Yamana Gold Inc.", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GGB", "ticker_tradingview": "NYSE:GGB", "name": "Gerdau S.A.", "region": ["US", "BR"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "VALE", "ticker_tradingview": "NYSE:VALE", "name": "Vale S.A.", "region": ["US", "BR"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BTI", "ticker_tradingview": "NYSE:BTI", "name": "British American Tobacco p.l.c.", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ABBV", "ticker_tradingview": "NYSE:ABBV", "name": "AbbVie Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MRK", "ticker_tradingview": "NYSE:MRK", "name": "Merck & Co., Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DIDI", "ticker_tradingview": "NASDAQ:DIDI", "name": "Didi Global Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ZM", "ticker_tradingview": "NASDAQ:ZM", "name": "Zoom Video Communications, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LUV", "ticker_tradingview": "NYSE:LUV", "name": "Southwest Airlines Co.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AAL", "ticker_tradingview": "NASDAQ:AAL", "name": "American Airlines Group Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "DAL", "ticker_tradingview": "NYSE:DAL", "name": "Delta Air Lines, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NIO", "ticker_tradingview": "NYSE:NIO", "name": "NIO Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "FSR", "ticker_tradingview": "NYSE:FSR", "name": "Fisker Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AMC", "ticker_tradingview": "NYSE:AMC", "name": "AMC Entertainment Holdings, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RBLX", "ticker_tradingview": "NYSE:RBLX", "name": "Roblox Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NET", "ticker_tradingview": "NYSE:NET", "name": "Cloudflare, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SNOW", "ticker_tradingview": "NYSE:SNOW", "name": "Snowflake Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NOW", "ticker_tradingview": "NYSE:NOW", "name": "ServiceNow, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ADBE", "ticker_tradingview": "NASDAQ:ADBE", "name": "Adobe Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SAP", "ticker_tradingview": "NYSE:SAP", "name": "SAP SE", "region": ["US", "DE"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BNS", "ticker_tradingview": "NYSE:BNS", "name": "The Bank of Nova Scotia", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RY", "ticker_tradingview": "NYSE:RY", "name": "Royal Bank of Canada", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TD", "ticker_tradingview": "NYSE:TD", "name": "The Toronto-Dominion Bank", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SU", "ticker_tradingview": "NYSE:SU", "name": "Suncor Energy Inc.", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ENB", "ticker_tradingview": "NYSE:ENB", "name": "Enbridge Inc.", "region": ["US", "CA"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BBD", "ticker_tradingview": "NYSE:BBD", "name": "Banco Bradesco S.A.", "region": ["US", "BR"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ITUB", "ticker_tradingview": "NYSE:ITUB", "name": "Itaú Unibanco Holding S.A.", "region": ["US", "BR"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "HSBC", "ticker_tradingview": "NYSE:HSBC", "name": "HSBC Holdings plc", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "VOD", "ticker_tradingview": "NASDAQ:VOD", "name": "Vodafone Group Plc", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BP", "ticker_tradingview": "NYSE:BP", "name": "BP p.l.c.", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SHEL", "ticker_tradingview": "NYSE:SHEL", "name": "Shell plc", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GLEN", "ticker_tradingview": "OTCMKTS:GLNCY", "name": "Glencore plc", "region": ["US", "CH", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RR", "ticker_tradingview": "OTCMKTS:RYCEY", "name": "Rolls-Royce Holdings plc", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GSK", "ticker_tradingview": "NYSE:GSK", "name": "GSK plc", "region": ["US", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RIO", "ticker_tradingview": "NYSE:RIO", "name": "Rio Tinto Group", "region": ["US", "AU", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BHP", "ticker_tradingview": "NYSE:BHP", "name": "BHP Group Limited", "region": ["US", "AU", "GB"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TM", "ticker_tradingview": "NYSE:TM", "name": "Toyota Motor Corporation", "region": ["US", "JP"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SONY", "ticker_tradingview": "NYSE:SONY", "name": "Sony Group Corporation", "region": ["US", "JP"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TCEHY", "ticker_tradingview": "OTCMKTS:TCEHY", "name": "Tencent Holdings Limited", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NTES", "ticker_tradingview": "NASDAQ:NTES", "name": "NetEase, Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BIDU", "ticker_tradingview": "NASDAQ:BIDU", "name": "Baidu, Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "PDD", "ticker_tradingview": "NASDAQ:PDD", "name": "PDD Holdings Inc.", "region": ["US", "CN"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WORK", "ticker_tradingview": "NASDAQ:WORK", "name": "Workday, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "ORCL", "ticker_tradingview": "NYSE:ORCL", "name": "Oracle Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MU", "ticker_tradingview": "NASDAQ:MU", "name": "Micron Technology, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "AVGO", "ticker_tradingview": "NASDAQ:AVGO", "name": "Broadcom Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "COF", "ticker_tradingview": "NYSE:COF", "name": "Capital One Financial Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WISH", "ticker_tradingview": "NASDAQ:WISH", "name": "ContextLogic Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NKLA", "ticker_tradingview": "NASDAQ:NKLA", "name": "Nikola Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WKHS", "ticker_tradingview": "NASDAQ:WKHS", "name": "Workhorse Group Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "BLNK", "ticker_tradingview": "NASDAQ:BLNK", "name": "Blink Charging Co.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RCL", "ticker_tradingview": "NYSE:RCL", "name": "Royal Caribbean Group", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CCL", "ticker_tradingview": "NYSE:CCL", "name": "Carnival Corporation & plc", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NCLH", "ticker_tradingview": "NYSE:NCLH", "name": "Norwegian Cruise Line Holdings Ltd.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WYNN", "ticker_tradingview": "NASDAQ:WYNN", "name": "Wynn Resorts, Limited", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MGM", "ticker_tradingview": "NYSE:MGM", "name": "MGM Resorts International", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LVS", "ticker_tradingview": "NYSE:LVS", "name": "Las Vegas Sands Corp.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "GOOG", "ticker_tradingview": "NASDAQ:GOOG", "name": "Alphabet Inc. (Class C)", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CVX", "ticker_tradingview": "NYSE:CVX", "name": "Chevron Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LMT", "ticker_tradingview": "NYSE:LMT", "name": "Lockheed Martin Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "RTX", "ticker_tradingview": "NYSE:RTX", "name": "RTX Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "NOC", "ticker_tradingview": "NYSE:NOC", "name": "Northrop Grumman Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "LOW", "ticker_tradingview": "NYSE:LOW", "name": "Lowe's Companies, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "TGT", "ticker_tradingview": "NYSE:TGT", "name": "Target Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "WBA", "ticker_tradingview": "NASDAQ:WBA", "name": "Walgreens Boots Alliance, Inc.", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "CVS", "ticker_tradingview": "NYSE:CVS", "name": "CVS Health Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "UNH", "ticker_tradingview": "NYSE:UNH", "name": "UnitedHealth Group Incorporated", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "MDT", "ticker_tradingview": "NYSE:MDT", "name": "Medtronic plc", "region": ["US", "IE"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False},
        {"ticker": "SYK", "ticker_tradingview": "NYSE:SYK", "name": "Stryker Corporation", "region": ["US"], "prompt": EQ_EQUITY_LONG_SHORT_PROMPT, "factors": EQ_EQUITY_FACTORS_PROMPT, "model_function": "run_holistic_market_model", "model_name": "holistic", "asset_class": "EQ", "importance": 4, "recurrence": "multi", "decimal": 2, "document_generated": False}
    ]
    
    try:
        collection = db[collection_name]
        
        # Check if any equities already exist to avoid duplicates
        existing_count = collection.count_documents({"ticker": {"$in": [equity["ticker"] for equity in equities]}})
        if existing_count > 0:
            print(f"Found {existing_count} existing equities. Skipping insertion to avoid duplicates.")
            return True
        
        # Insert all equities
        result = collection.insert_many(equities)
        print(f"Successfully inserted {len(result.inserted_ids)} equities into '{collection_name}' collection")
        return True
        
    except pymongo.errors.OperationFailure as e:
        log_error("MongoDB operation failed for inserting equities", "MONGODB_OPERATION", e)
        return False
    except Exception as e:
        log_error("Unexpected error inserting equities", "DATA_INSERTION", e)
        return False