name: ago-core-data-scheduled-runs

on:
  workflow_dispatch:
  #schedule:
  #   - cron: '30 0,5,10,15 * * *'  # Batch runs at 00:30, 05:30, 10:30, 15:30 UTC
  #   - cron: '0 23 * * *'          # Reset run at 23:00 UTC

jobs:
  batch_run:
    runs-on: ubuntu-latest
    if: github.event.schedule == '30 0,5,10,15 * * *'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run batch processing - data collection
      run: python main.py -batch

  reset_run:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 23 * * *'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run reset dataset
      run: python main.py -reset